#
# Jekyll configuration
#
auto: true
permalink: /:title
pygments: true
lsi: true
markdown: rdiscount
rdiscount
  extensions: [smart]

#
# Site configuration
#
base_url: http://skeleton.tagada.hu # L'URL de votre site
url: http://skeleton.tagada.hu # L'URL de votre site
title: "Jekyll Skeleton" # Titre de votre site
description: "Thème gratuit pour le générateur de site Jekyll" # La meta description sur la page d'accueil de votre site
author: "Jeremy Herve" # Votre nom
email: "jeremy@tagada.hu" # Votre email
gauaid: "UA-1697171-11" # Votre numéro de tracking Google Analytics
disqusshortname: "jekyllskeleton" # Votre Shortname Disqus