#
# Jekyll configuration
#
auto: true
permalink: /:title
pygments: true
lsi: true
markdown: rdiscount
rdiscount
  extensions: [smart]

#
# Site configuration
#
base_url: http://danielsmiller.com
url: http://danielsmiller.com # L'URL de votre site
title: "/home/dan" # Titre de votre site
description: "Dan Miller's Personal Website" # La meta description sur la page d'accueil de votre site
author: "Dan Miller" # Votre nom
email: "dan@danielsmiller.com" # Votre email
#gauaid: "UA-1697171-11" # Votre numéro de tracking Google Analytics
#disqusshortname: "danielsmillercom" # Votre Shortname Disqus
